[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor
    knolleary/PubSubClient@^2.8

